/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuldeep;

import jaco.mp3.player.MP3Player;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Pooja
 */
public class Choice extends javax.swing.JFrame {

 public static final String blns ="C:\\Users\\kuldeep\\Documents\\NetBeansProjects\\ATM\\src\\audio\\blnenq.mp3";
MP3Player mp3blns=new MP3Player(new File(blns));
public static final String atmbtn ="C:\\Users\\kuldeep\\Documents\\NetBeansProjects\\ATM\\src\\audio\\atmbtn.mp3";
MP3Player mp3atmbtn=new MP3Player(new File(atmbtn));

      
    /* * Creates new form Choice
     */
    public Choice() {
        initComponents();
        username();
       jLabel2.requestFocus();
        load1.setVisible(false);
             Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         UIManager.put("OptionPane.messageForeground", Color.BLUE);
          jPanel7.setBackground(new Color(0,0,0,200));
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        pinchange = new javax.swing.JButton();
        ministm = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        cashwithdraw = new javax.swing.JButton();
        blnenquiry = new javax.swing.JButton();
        cashdeposit = new javax.swing.JButton();
        un = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        load1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frame");
        setBackground(new java.awt.Color(102, 0, 102));
        setLocation(new java.awt.Point(200, 100));
        setName("frame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, -1, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 260, 20));

        jPanel7.setBackground(new java.awt.Color(0, 0, 200));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 244, 244));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please select your transaction");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -10, 660, 80));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 720, 60));

        jLabel3.setBackground(new java.awt.Color(244, 244, 244));
        jLabel3.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(244, 244, 244));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ATM SYSTEM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 490, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 1170, 20));

        pinchange.setBackground(new java.awt.Color(0, 102, 0));
        pinchange.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        pinchange.setText("Pin Change");
        pinchange.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pinchange.setMaximumSize(new java.awt.Dimension(153, 29));
        pinchange.setMinimumSize(new java.awt.Dimension(153, 29));
        pinchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinchangeActionPerformed(evt);
            }
        });
        getContentPane().add(pinchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 340, 50));

        ministm.setBackground(new java.awt.Color(0, 102, 0));
        ministm.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ministm.setText("MINI STATEMENT");
        ministm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ministm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ministmActionPerformed(evt);
            }
        });
        getContentPane().add(ministm, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 340, 50));

        Logout.setBackground(new java.awt.Color(153, 0, 0));
        Logout.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Logout.setText("Logout");
        Logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, 340, 50));

        cashwithdraw.setBackground(new java.awt.Color(0, 102, 0));
        cashwithdraw.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cashwithdraw.setText("Cash Withdrawal");
        cashwithdraw.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cashwithdraw.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cashwithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashwithdrawActionPerformed(evt);
            }
        });
        getContentPane().add(cashwithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 340, 50));

        blnenquiry.setBackground(new java.awt.Color(0, 102, 0));
        blnenquiry.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        blnenquiry.setText("Balance Enquiry");
        blnenquiry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        blnenquiry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                blnenquiryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                blnenquiryFocusLost(evt);
            }
        });
        blnenquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blnenquiryActionPerformed(evt);
            }
        });
        getContentPane().add(blnenquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 340, 50));

        cashdeposit.setBackground(new java.awt.Color(0, 102, 0));
        cashdeposit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cashdeposit.setText("Cash Deposit");
        cashdeposit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cashdeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashdepositActionPerformed(evt);
            }
        });
        getContentPane().add(cashdeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 340, 50));

        un.setBackground(new java.awt.Color(51, 51, 51));
        un.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        un.setForeground(new java.awt.Color(244, 244, 244));
        un.setText("Welcome");
        getContentPane().add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 560, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loader.gif"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, 290));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("SAE BANK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 130, 40));

        load1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/load.gif"))); // NOI18N
        getContentPane().add(load1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/589298.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 670));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void username()
{int u=0;
      String n="";
  try{   
      
      Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql2 = "Select cardnumber from atmsystem";
                
               PreparedStatement pstmt2 = conn2.prepareStatement(sql2);                        
                
           
             ResultSet rs2= pstmt2.executeQuery();
             if(rs2.next())
             {
                 u=rs2.getInt("cardnumber");
             }
            
              
            
            Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql1 = "select name from  user where cno=?  ";
                
               PreparedStatement pstmt1 = conn.prepareStatement(sql1);                        
                 
               
            pstmt1.setInt(1 , u);
               ResultSet rs = pstmt1.executeQuery();
               
              
            
               if(rs.next())
               {
                  n=rs.getString("name");
                  un.setText("Welcome "+n); 
               }
            
           
}   
 
  catch(Exception e){
  JOptionPane.showMessageDialog(this,e);
  }
             
}

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
mp3atmbtn.play();
        try{Thread.sleep(800);}
catch(Exception e)
        {}                 
         new Login().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void blnenquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blnenquiryActionPerformed
un.requestFocus();
mp3atmbtn.play();        try{   
         Thread.sleep(800);
           mp3blns.play();
           int u=0;
            int bl=0,b2=0;int amt1=0;
            
             Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql2 = "Select cardnumber from atmsystem";
                
               PreparedStatement pstmt2 = conn2.prepareStatement(sql2);                        
                
           
             ResultSet rs2= pstmt2.executeQuery();
             if(rs2.next())
             {
                 u=rs2.getInt("cardnumber");
             }
            
            
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql1 = "select acno from  user where cno=?  ";
                
               PreparedStatement pstmt1 = conn.prepareStatement(sql1);                        
                 
               
            pstmt1.setInt(1 , u);
               ResultSet rs = pstmt1.executeQuery();
               
              
            
               if(rs.next())
               {
                  b2=rs.getInt("acno");
                 
               }
               
               
               
               Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql3 = "select bal from  account where ano=?  ";
                
               PreparedStatement pstmt3 = conn1.prepareStatement(sql3);                        
                 
               
            pstmt3.setInt(1 , b2);
               ResultSet rs3 = pstmt3.executeQuery();
               
              
            
               if(rs3.next())
               {
                  bl=rs3.getInt("bal");
                 
               }
               
              
               
             
                
               
                 
               
               
               JOptionPane.showMessageDialog(this,"Your Balance is : "+bl);
               new Choice().setVisible(true);
               this.dispose();
                 
              
                
        }
        
        catch(Exception e)
           {
            JOptionPane.showMessageDialog(this,e);
            
           }  

      
    }//GEN-LAST:event_blnenquiryActionPerformed

    private void cashwithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashwithdrawActionPerformed
mp3atmbtn.play(); 
try{Thread.sleep(800);}
catch(Exception e)
        {}
        new withdraw().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_cashwithdrawActionPerformed

    private void pinchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinchangeActionPerformed
mp3atmbtn.play();
        try{Thread.sleep(800);}
catch(Exception e)
        {}     
        new pinchange().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_pinchangeActionPerformed

    private void ministmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ministmActionPerformed
        // TODO add your handling code here:
      
       new transcationDisplay().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ministmActionPerformed

    private void cashdepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashdepositActionPerformed
mp3atmbtn.play();  try{Thread.sleep(800);}
catch(Exception e)
        {}       new deposit().setVisible(true);
         this.dispose();
        
    }//GEN-LAST:event_cashdepositActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_formWindowActivated

    private void blnenquiryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_blnenquiryFocusGained
        // TODO add your handling code here:
         un.setVisible(false);
        load1.setVisible(true);
    }//GEN-LAST:event_blnenquiryFocusGained

    private void blnenquiryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_blnenquiryFocusLost
          load1.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_blnenquiryFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Choice().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton blnenquiry;
    private javax.swing.JButton cashdeposit;
    private javax.swing.JButton cashwithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel load1;
    private javax.swing.JButton ministm;
    private javax.swing.JButton pinchange;
    private javax.swing.JLabel un;
    // End of variables declaration//GEN-END:variables
}
