/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuldeep;

import jaco.mp3.player.MP3Player;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Pooja
 */
public class Login extends javax.swing.JFrame {
public static final String song ="C:\\Users\\kuldeep\\Documents\\NetBeansProjects\\ATM\\src\\audio\\welcome.mp3";
MP3Player mp3player=new MP3Player(new File(song));
public static final String penter ="C:\\Users\\kuldeep\\Documents\\NetBeansProjects\\ATM\\src\\audio\\enterpinnid.mp3";
MP3Player mp3penter=new MP3Player(new File(penter));



public static final String inlogin ="C:\\Users\\kuldeep\\Documents\\NetBeansProjects\\ATM\\src\\audio\\invaildlogin.mp3";
MP3Player mp3inlogin=new MP3Player(new File(inlogin));
public static final String logindone ="C:\\Users\\kuldeep\\Documents\\NetBeansProjects\\ATM\\src\\audio\\logindone.mp3";
MP3Player mp3logindone=new MP3Player(new File(logindone));
public static final String user ="C:\\Users\\kuldeep\\Documents\\NetBeansProjects\\ATM\\src\\audio\\UserLogin_1.mp3";
MP3Player mp3user=new MP3Player(new File(user));
public static final String atmbtn ="C:\\Users\\kuldeep\\Documents\\NetBeansProjects\\ATM\\src\\audio\\atmbtn.mp3";
MP3Player mp3atmbtn=new MP3Player(new File(atmbtn));
 
  /**
     * Creates new form Login
     */
    public Login() {mp3player.play();
        initComponents();
        load1.setVisible(false);
         userid.setFocusable(true);
        pnl_overlay.setBackground(new Color(0,0,0,200));
     
        groupButton( ) ;
        userpin.setVisible(false);
            UIManager.put("OptionPane.messageForeground", Color.BLUE);
	     Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);	
    

    




    
    }
    private void groupButton() 
    {

ButtonGroup bg1 = new ButtonGroup( );
 
bg1.add(rb1);
bg1.add(rb2);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        load1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        userid = new javax.swing.JTextField();
        lid = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        userpin = new javax.swing.JPasswordField();
        lpin = new javax.swing.JLabel();
        pnl_overlay = new javax.swing.JPanel();
        load = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        load1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/load.gif"))); // NOI18N
        jPanel2.add(load1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Atm management System ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 450, -1));

        rb1.setBackground(new java.awt.Color(51, 51, 51));
        rb1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        rb1.setForeground(new java.awt.Color(255, 255, 255));
        rb1.setSelected(true);
        rb1.setText("USER");
        rb1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        jPanel2.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        rb2.setBackground(new java.awt.Color(51, 51, 51));
        rb2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        rb2.setForeground(new java.awt.Color(255, 255, 255));
        rb2.setText("ADMIN");
        rb2.setToolTipText("");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jPanel2.add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        userid.setBackground(new java.awt.Color(51, 51, 51));
        userid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userid.setForeground(new java.awt.Color(255, 255, 255));
        userid.setToolTipText("Card ID");
        userid.setBorder(null);
        userid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                useridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                useridFocusLost(evt);
            }
        });
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        userid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                useridKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                useridKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                useridKeyTyped(evt);
            }
        });
        jPanel2.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 217, 20));

        lid.setBackground(new java.awt.Color(255, 255, 255));
        lid.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        lid.setForeground(new java.awt.Color(255, 255, 255));
        lid.setText("Card ID");
        jPanel2.add(lid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jButton1ItemStateChanged(evt);
            }
        });
        jButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton1StateChanged(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton1FocusLost(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 319, 80, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 217, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 217, 10));

        userpin.setBackground(new java.awt.Color(51, 51, 51));
        userpin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userpin.setForeground(new java.awt.Color(255, 255, 255));
        userpin.setBorder(null);
        userpin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userpinFocusGained(evt);
            }
        });
        userpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpinActionPerformed(evt);
            }
        });
        userpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userpinKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userpinKeyTyped(evt);
            }
        });
        jPanel2.add(userpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 217, 20));

        lpin.setBackground(new java.awt.Color(255, 255, 255));
        lpin.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        lpin.setForeground(new java.awt.Color(255, 255, 255));
        lpin.setText("Card Pin");
        jPanel2.add(lpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 480, 460));

        pnl_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        load.setBackground(new java.awt.Color(51, 204, 255));
        load.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        load.setForeground(new java.awt.Color(0, 0, 153));
        load.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        load.setText("MINI PROJECT");
        pnl_overlay.add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 450, -1));

        jLabel9.setBackground(new java.awt.Color(51, 204, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Atm management system");
        pnl_overlay.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 450, 40));

        getContentPane().add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 460));

        image.setBackground(new java.awt.Color(0, 0, 200));
        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\kuldeep\\Desktop\\atm images\\login.jpg")); // NOI18N
        image.setText("jLabel1");
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 480, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


     
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userid.requestFocusInWindow();
       if( userid.getText().isEmpty())
        {
            
           
         JOptionPane.showMessageDialog(this,"Enter ID","Alert",JOptionPane.WARNING_MESSAGE);
           
            
         
        }

  
        else if( userpin.getText().isEmpty())
        {
            
            
          
         JOptionPane.showMessageDialog(this,"Enter PIN","Alert",JOptionPane.WARNING_MESSAGE);
           
            
        }
   
        else{   try{
           
          

           mp3atmbtn.play();     
               
              
               
       if(rb1.isSelected())         
                  
       {  
            
             int u=0,l=0;
    
         Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql = "select *from  user where cno=? ";
               PreparedStatement pstmt = conn.prepareStatement(sql);                        
                 
                pstmt.setInt(1,Integer.parseInt(userid.getText()));
               ResultSet rs = pstmt.executeQuery();
               
              
            
               if(rs.next())
               {
                  u=rs.getInt("cno");
                 
               }
              
              
               
               
               
                Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
              String sql1 = "select *from  card where cardpin=? ";
               PreparedStatement pstmt1 = conn1.prepareStatement(sql1);                        
                  pstmt1.setInt(1,Integer.parseInt(userpin.getText()));
                  
                   
                
               ResultSet rs1 = pstmt1.executeQuery();
              if(rs1.next())
              {
                  l=rs1.getInt("cardpin");
                  
          
              }
              
              
         
           int useid=Integer.parseInt(userid.getText());
           int usepin=Integer.parseInt(userpin.getText());
           
           
           
           if(useid==u && usepin==l)            
        {
                int n=0; int id=0; String add="";
              Class.forName("com.mysql.cj.jdbc.Driver");
               Connection connf = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sqlf = "select * from  atmsystem  ";
                
               PreparedStatement pstmtf = connf.prepareStatement(sqlf);                        
                 
               
         
               ResultSet rsf = pstmtf.executeQuery();
               
              
            
               if(rsf.next())
               {
                  n=rsf.getInt("cardnumber");
                  id=rsf.getInt("idatm");       
                  add=rsf.getString("address");
                 
                 
               }
           if(n==0 && id==0 && add.isEmpty()){ 
            Class.forName("com.mysql.cj.jdbc.Driver");
           
               Connection conn2i = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql2i = "insert into atmsystem (idatm,cardnumber,address)values(?,?,?)";
                
               PreparedStatement pstmt2i = conn2i.prepareStatement(sql2i);                        
                 pstmt2i.setInt(1,1);
               pstmt2i.setInt(2,u);
               pstmt2i.setString(3,"Pune");
               
               
           
              pstmt2i.executeUpdate();}
            
            
                Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql2 = "update atmsystem set idatm=?,cardnumber=?,address=?";
                
               PreparedStatement pstmt2 = conn2.prepareStatement(sql2);                        
                     pstmt2.setInt(1,1);
               pstmt2.setInt(2,u);
               pstmt2.setString(3,"Pune");
           
              pstmt2.executeUpdate();
              mp3logindone.play();
              
              UIManager.put("OptionPane.messageForeground", Color.BLUE);
              
            JOptionPane.showMessageDialog(this,"Logged In Successfully");
            mp3logindone.stop();
            mp3user.play();
            new Choice().setVisible(true);
           
               
            userpin.setText("");
          
            this.dispose();
        }
           
          
           
        else
        {               mp3inlogin.play();
         UIManager um = new UIManager(); 
                     um.put("OptionPane.messageForeground", Color.BLUE);
                      userpin.setVisible(false);
                     
                     JOptionPane.showMessageDialog(this,"Invaild ID or PIN Please Try Again", "Error", JOptionPane.ERROR_MESSAGE);
            userpin.setText("");
            userid.setText("");

         
        } 
       }   
        else if(rb2.isSelected())
       {
           userpin.setVisible(false);
       if("2019".equals(userid.getText())&&"2020".equals(userpin.getText()))        
        { 
           mp3logindone.play();
 UIManager um = new UIManager(); 
 um.put("OptionPane.messageForeground", Color.BLUE);
 
            JOptionPane.showMessageDialog(this,"Logged In Successfully");
            new admin().setVisible(true);
            userpin.setText("");
          
            this.dispose();}
         else
       { mp3inlogin.play();
       
         userpin.setVisible(false);
         
            JOptionPane.showMessageDialog(this,"Invaild Pin or ID", "Error", JOptionPane.ERROR_MESSAGE);
            userpin.setText("");
            userid.setText("");}
            
        }
       
   /*   
        else
        {
            JOptionPane.showMessageDialog(this,"Invaild ID or PIN Please Try Again");
            userpin.setText("");
            userid.setText("");
         
        } */
       
       
       
       
       
       
        
    }
         catch(Exception e)
           {
            mp3penter.play();  
             userpin.setVisible(false);
             
            JOptionPane.showMessageDialog(this,e);
            userpin.setText("");
            userid.setText("");
           }
        
        }
        
        
   
        
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
mp3atmbtn.play();        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
        userid.setText("");
        userpin.setText("");
     lid.setText("Admin ID");
           lpin.setText("Admin Pin");
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
      lid.setText("Card ID");
           lpin.setText("Card Pin");
    }//GEN-LAST:event_rb1ActionPerformed

    private void userpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userpinActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void useridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyPressed
        // TODO add your handling code here:
      
     
     // mp3atmbtn.play();
       
    
    }//GEN-LAST:event_useridKeyPressed

    private void useridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_useridFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_useridFocusGained

    private void useridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_useridFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_useridFocusLost

    private void useridKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyTyped
        // TODO add your handling code here:
        
        
        char key;
        key=evt.getKeyChar();
        
        if(  !(((key>='0') && (key<='9')))  && (key!='\b'))
        evt.consume();

if(userid.getText().length()>=10) {  
   evt.consume();}
   
        userpin.setVisible(true);
    }//GEN-LAST:event_useridKeyTyped

    private void userpinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userpinKeyTyped
        // TODO add your handling code here:
        char key;
        key=evt.getKeyChar();
        
        if(  !(((key>='0') && (key<='9')))  && (key!='\b'))
        evt.consume();

if(userpin.getText().length()>=10) {  
   evt.consume();}
   
    }//GEN-LAST:event_userpinKeyTyped

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jButton1KeyPressed

    private void userpinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userpinKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userpinKeyPressed

    private void userpinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userpinFocusGained
        // TODO add your handling code here:
      if(userid.getText().equals(""))  
      {userpin.setVisible(false);}
      else
      {userpin.setVisible(true);}
    }//GEN-LAST:event_userpinFocusGained

    private void useridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyReleased
   mp3atmbtn.stop();         // TODO add your handling code here:
    }//GEN-LAST:event_useridKeyReleased

    private void jButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1StateChanged

    private void jButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButton1ItemStateChanged
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ItemStateChanged

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
load1.setVisible(true);  

// TODO add your handling code here:*/
    }//GEN-LAST:event_jButton1FocusGained

    private void jButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusLost
load1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel load;
    private javax.swing.JLabel load1;
    private javax.swing.JLabel lpin;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField userid;
    private javax.swing.JPasswordField userpin;
    // End of variables declaration//GEN-END:variables
}
