/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuldeep;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kuldeep
 */
public class transcationDisplay extends javax.swing.JFrame {
   int u=0;
            int bl=0,b2=0;int uid=0;
    /**
     * Creates new form transcationDisplay
     */
    public transcationDisplay() {
        initComponents();
              Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        trans();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(244, 244, 244));
        jLabel3.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("All Transaction ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 490, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "T_ID", "DATE", "User_id", "REMARK", "DEBIT/CREDIT", "AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 49, 1028, 475));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 530, 225, 39));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        new Choice().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
private void trans(){


     try
        {
            
         
            
             Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql2 = "Select cardnumber from atmsystem";
                
               PreparedStatement pstmt2 = conn2.prepareStatement(sql2);                        
                
           
             ResultSet rs2= pstmt2.executeQuery();
             if(rs2.next())
             {
                 u=rs2.getInt("cardnumber");
             }
            
            
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sql1 = "select acno from  user where cno=?  ";
                
               PreparedStatement pstmt1 = conn.prepareStatement(sql1);                        
                 
               
            pstmt1.setInt(1 , u);
               ResultSet rs = pstmt1.executeQuery();
               
              
            
               if(rs.next())
               {
                  b2=rs.getInt("acno");
                 
               }
                  
             Class.forName("com.mysql.cj.jdbc.Driver");
               Connection connu = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                String sqlu = "select user_id from  user where acno=?  ";
                
               PreparedStatement pstmtu = connu.prepareStatement(sqlu);                        
                 
               
            pstmtu.setInt(1 , b2);
               ResultSet rsu= pstmtu.executeQuery();
               
              
            
               if(rsu.next())
               {
                  uid=rsu.getInt("user_id");
                 
               }
           Class.forName("com.mysql.jdbc.Driver");
               Connection connd = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","mysql");
                 String sqld = "select * from  transaction where userid=? ; ";
                
               PreparedStatement pstmtd = connd.prepareStatement(sqld); 
               pstmtd.setInt(1,uid);
                ResultSet rsd = pstmtd.executeQuery();
                DefaultTableModel tm = (DefaultTableModel)table1.getModel();
              
                while(rsd.next())               
                {
                  Object o[] = {rsd.getInt("td"),rsd.getString("date"),rsd.getInt("userid"),rsd.getString("remark"),rsd.getString("dc"),rsd.getInt("amount")};
                  tm.addRow(o);
                
                }
        }
        catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }



}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transcationDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transcationDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transcationDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transcationDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transcationDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
